version: "3"
services:
  app:
    container_name: spring-boot-graphql_app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/usr/local/app
    tty: true
    ports:
      - 8080:8080
    environment:
      DB_URL: db:5432
  db:
    container_name: spring-boot-graphql_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/posrgresql/data
volumes:
  db_data:
